name: Update Naver JSON

on:
  schedule:
    - cron: "0 * * * *" # jalan tiap jam
  workflow_dispatch: # bisa manual dari GitHub Actions tab

jobs:
  update-naver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install puppeteer

      - name: Run Puppeteer Scraper
        run: node naver_update.js

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "action@github.com"
          git add naver.json
          git commit -m "Auto update naver.json" || echo "No changes to commit"
          git push
