name: Update VolleyballWorld JSON

on:
  schedule:
    - cron: "*/10 * * * *" # jalan tiap 10 menit
  workflow_dispatch:       # bisa dijalankan manual juga

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python volleyballworld/scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add volleyballworld.json
          git commit -m "Auto update volleyballworld.json" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
