name: Update VolleyballWorld JSON

on:
  schedule:
    - cron: "*/10 * * * *"   # jalan tiap 10 menit
  workflow_dispatch:          # bisa dijalankan manual

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python scraper.py

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add volleyballworld.json
          git commit -m "Auto update volleyballworld.json" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/GameonxProject/polimania.git HEAD:main
