name: Update Volleyball JSON

on:
  schedule:
    - cron: "*/30 * * * *"   # setiap 30 menit
  workflow_dispatch:         # bisa manual run juga

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python scraper.py

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add volleyballworld.json
          git commit -m "Auto update volleyballworld.json" || echo "No changes"
          git push
